--4장 연습문제
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;


--2번
SELECT STUDENT.STU_NO, STU_NAME, SUBJECT.SUB_NAME, ENR_GRADE
FROM STUDENT, SUBJECT, ENROL
WHERE STUDENT.STU_DEPT = SUBJECT.SUB_DEPT
ORDER BY 1;

--4번
SELECT SUB_NAME, STU_NO, SUB_GRADE
FROM SUBJECT JOIN STUDENT USING(SUB_DEPT);

--6번
SELECT STU_NAME, ENR_GRADE
FROM STUDENT JOIN ENROL USING(STU_NO)
WHERE ENR_GRADE > 60;

--8번
SELECT STU_NAME, SUB_NAME, SUB_PROF
FROM STUDENT, SUBJECT
WHERE STUDENT.STU_DEPT=SUBJECT.SUB_DEPT
AND STU_NAME = '김인중';

--10번
SELECT STU_NAME, SUB_NAME, SUB_PROF
FROM STUDENT JOIN ENROL USING(STU_NO) JOIN SUBJECT USING(SUB_NO)
WHERE STU_NAME = '김인중';