--4장 실전문제(짝수)
SELECT * FROM EMP;
SELECT * FROM DEPT;

--2
SELECT EMP.EMPNO, ENAME, DEPT.DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO;

--4
SELECT EMPNO, ENAME, DEPT.DNAME
FROM EMP JOIN DEPT USING(DEPTNO);

--6
SELECT ENAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND LOC = 'NEW YORK';

--8
SELECT ENAME, LOC
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE LOC = 'NEW YORK';

--10
SELECT EMPNO, ENAME, LOC
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE LOC = 'NEW YORK'
ORDER BY 1;

--12
SELECT ENAME, DNAME, LOC
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE ENAME = 'ADAMS';

--14
SELECT ENAME, DNAME, LOC
FROM EMP NATURAL JOIN DEPT
WHERE ENAME = 'ADAMS';

--16
SELECT EMPNO, ENAME, DNAME, SAL
FROM EMP, DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO
AND SAL BETWEEN 1000 AND 2000
ORDER BY 1;

SELECT EMPNO, ENAME, DNAME, SAL
FROM EMP NATURAL JOIN DEPT
WHERE SAL BETWEEN 1000 AND 2000
ORDER BY 1;

SELECT EMPNO, ENAME, DNAME, SAL
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE SAL BETWEEN 1000 AND 2000
ORDER BY 1;

SELECT EMPNO, ENAME, DNAME, SAL
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL BETWEEN 1000 AND 2000
ORDER BY 1;

--18
SELECT EMPNO, ENAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO
AND LOC IN('NEW YORK','DALLAS')
ORDER BY 1;

--20
SELECT EMPNO, ENAME, LOC
FROM EMP NATURAL JOIN DEPT
WHERE LOC IN ('NEW YORK','DALLAS')
ORDER BY 1;

--22
SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP, SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL
ORDER BY 4, 1;

--24
SELECT A.EMPNO, A.ENAME, B.EMPNO, B.ENAME
FROM EMP A JOIN EMP B ON A.MGR=B.EMPNO;

--26
SELECT B.ENAME, B.SAL
FROM EMP A, EMP B
WHERE B.SAL > A.SAL
AND A.ENAME = 'BLAKE';

--28
SELECT EMPNO
FROM EMP
WHERE SAL =(SELECT SAL FROM EMP 
WHERE ENAME ='FORD');

--30
SELECT B.EMPNO, B.ENAME, COUNT(*)
FROM EMP A JOIN EMP B ON A.MGR = B.EMPNO
GROUP BY B.EMPNO, B.ENAME, A.MGR
ORDER BY 3 DESC;

--32
SELECT *
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME ='SCOTT');

--34
SELECT *
FROM EMP WHERE DEPTNO <>20
AND JOB IN (SELECT JOB FROM EMP WHERE DEPTNO =20);

--36
SELECT *
FROM EMP 
WHERE SAL >ALL(SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO);

--38
SELECT *
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO');





