CREATE TABLE A_ENROL
AS SELECT * FROM ENROL
WHERE STU_NO < 20150000;

SELECT * FROM A_ENROL;

INSERT INTO A_ENROL(SUB_NO, STU_NO, ENR_GRADE)
VALUES(108, 20151062, 92);

INSERT INTO A_ENROL
VALUES(109, 20152088,85);

INSERT INTO A_ENROL(SUB_NO, STU_NO)
VALUES(110, 20152088);

SELECT * FROM A_ENROL; --에러뜸

INSERT INTO A_ENROL
VALUES(111,20153075, NULL);

SELECT * FROM A_ENROL;

SELECT * FROM ENROL;

SELECT * FROM ENROL
WHERE STU_NO LIKE '2015%';

INSERT INTO A_ENROL
SELECT * FROM ENROL
WHERE STU_NO LIKE '2015%';

SELECT * FROM A_ENROL;

UPDATE A_ENROL
SET ENR_GRADE = ENR_GRADE +5;

SELECT * FROM A_ENROL;

UPDATE A_ENROL
SET ENR_GRADE = ENR_GRADE +5
WHERE SUB_NO = 101;

SELECT * FROM A_ENROL;
--------------------------------------------172PAGE
UPDATE A_ENROL
SET ENR_GRADE = ENR_GRADE + 10
WHERE SUB_NO = (SELECT SUB_NO FROM SUBJECT WHERE SUB_NAME ='시스템분석설계');

SELECT * FROM A_ENROL;


--DELETE 
DELETE FROM A_ENROL
WHERE STU_NO = 20131001;

DELETE A_ENROL
WHERE SUB_NO = (SELECT SUB_NO FROM SUBJECT WHERE SUB_NAME = '기계요소설계');

DELETE FROM A_ENROL;

----MERGE 

MERGE INTO A_STUDENT A 
    USING STUDENT S 
ON (S.STU_NO = A.STU_NO)
WHEN MATCHED THEN 
    UPDATE SET A.STU_WEIGHT = S.STU_WEIGHT
WHEN NOT MATCHED THEN 
    INSERT VALUES(S.STU_NO, S.STU_NAME, S.STU_DEPT, NULL,
        NULL,NULL,NULL,S.STU_WEIGHT);

SELECT * FROM A_STUDENT;

--TCL

SELECT * FROM B_STUDENT;

DELETE FROM B_STUDENT;

SELECT * FROM B_STUDENT;

ROLLBACK;

SELECT * FROM B_STUDENT;

DELETE FROM B_STUDENT;

CREATE TABLE C_STUDENT(STU_NO NUMBER, STU_AME CHAR(10));

ROLLBACK;

SELECT * FROM B_STUDENT;

SELECT * FROM A_STUDENT;

DELETE FROM A_STUDENT;

SELECT * FROM A_STUDENT;

SELECT * FROM A_STUDENT;


